# fly.toml file generated for rduga on 2023-01-17T21:36:27+03:00

app = "rduga"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[mounts]
  source = "raduga_data"
  destination = "/data"

[env]
  PHX_HOST = "rduga.fly.dev"
  DATABASE_PATH = "/data/raduga_data/raduga_prod.db"
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
